apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-3scale-app
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: noprod
          - list:
              elements:
                - namespace: 3scale-tenant-dev
                - namespace: 3scale-tenant-testing
  template:
    metadata:
      name: "{{name}}-{{namespace}}-app"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-3scale-app.git
        targetRevision: develop
        path: "./overlays/noprod/{{namespace}}"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      #syncPolicy:
      # automated:
      #   prune: true
      #   selfHeal: true
