apiVersion: v1
kind: Secret
metadata:
  name: applicationauth-sample-api-key-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
stringData:
  UserKey: "2ef770a24954032e99dd02cf775ff6ff"
