apiVersion: v1
kind: Secret
metadata:
  name: developeruser-admin-testing-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
stringData:
  password: "redhat"
