apiVersion: batch/v1
kind: Job
metadata:
  name: reconcile-application
  annotations:
    #argocd.argoproj.io/sync-options: Delete
    argocd.argoproj.io/sync-options: Prune
spec:
  template:
    spec:
      containers:
        - name: reconcile
          image: registry.redhat.io/ubi8/python-312:latest
          command: ["python", "/config/reconcile_apps.py"]
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
            - name: apps-volume
              mountPath: /apps
              readOnly: true
          envFrom:
            - secretRef:
                name: dev-tenant-secret
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: reconcile-script
        - name: apps-volume
          secret:
            secretName: reconcile-application-secret
  backoffLimit: 2
