apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hook/operator_pre-hook.yaml

  - developer-accounts/developeraccount-devsecops-uat.yaml
  - developer-users/developeruser-lfalero-uat-secret.yaml
  - developer-users/developeruser-lfalero-uat.yaml

  - backends/bs-hello-java.yaml

  - products/bs-hello-java-openid-secret.yaml
  - products/bs-hello-java-openid.yaml
  - applications/application-sample-openid.yaml
