apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hook/operator_pre-hook.yaml
  - hook/operator_post-hook.yaml

  - developer-accounts/developeraccount-devsecops.yaml
  - developer-users/developeruser-admin-secret.yaml
  - developer-users/developeruser-admin.yaml

  - backends/bs-hello-java.yaml

  - products/bs-hello-java-openid-secret.yaml
  - products/bs-hello-java-openid.yaml
  - applications/application-sample-openid.yaml
