kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: developeruser-lfalero-dev
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  username: lfalero-dev
  passwordCredentialsRef:
    name: developeruser-lfalero-dev-secret
  email: lfalero-dev@redhat.com
  role: admin
  developerAccountRef:
    name: developeraccount-devsecops-dev
  providerAccountRef:
    name: dev-tenant-secret
