kind: Product
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: bs-hello-java-openid
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: "API Key BS Hello Java"
  systemName: bs_hello_java_api_key_product
  description: "Backend del servicio Hello Java expuesto internamente a través de Service en OpenShift."
  providerAccountRef:
    name: uat-tenant-secret

  deployment:
    apicastSelfManaged:
      stagingPublicBaseURL: "https://bs-hello-java-openid-staging.apps.cluster-z44mr.z44mr.sandbox3222.opentlc.com"
      productionPublicBaseURL: "https://bs-hello-java-openid.apps.cluster-z44mr.z44mr.sandbox3222.opentlc.com"
      authentication:
        oidc:
          authenticationFlow:
            standardFlowEnabled: true
            implicitFlowEnabled: false
            serviceAccountsEnabled: false            
            directAccessGrantsEnabled: false
          credentials: headers
          issuerType: keycloak
          issuerEndpointRef:
            name: bs-hello-java-openid-secret
          jwtClaimWithClientID: azp
          jwtClaimWithClientIDType: plain

  backendUsages:
    bs_hello_java_backend:
      path: "/"

  methods:
    get_hello_v1:
      friendlyName: "GET Hello V1"
      description: ""
    get_hello_v2:
      friendlyName: "GET Hello V2"
      description: ""
    get_date_v1:
      friendlyName: "GET Date V1"
      description: ""
    get_date_v2:
      friendlyName: "GET Date V2"
      description: ""

  mappingRules:
    - httpMethod: GET
      pattern: "/bs/v1/hello"
      metricMethodRef: get_hello_v1
      increment: 1
      last: true
    - httpMethod: GET
      pattern: "/bs/v2/hello"
      metricMethodRef: get_hello_v2
      increment: 1
      last: true
    - httpMethod: GET
      pattern: "/bs/v1/date"
      metricMethodRef: get_date_v1
      increment: 1
      last: true
    - httpMethod: GET
      pattern: "/bs/v2/date"
      metricMethodRef: get_date_v2
      increment: 1
      last: true

  applicationPlans:
    basic:
      name: Basic
      appsRequireApproval: false
      trialPeriod: 0
      setupFee: "0.00"
      costMonth: "0.00"
      custom: false
      state: published
