kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: developeruser-admin-uat
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  username: admin-uat
  passwordCredentialsRef:
    name: developeruser-admin-uat-secret
  email: admin-uat@redhat.com
  role: admin
  developerAccountRef:
    name: developeraccount-devsecops-uat
  providerAccountRef:
    name: uat-tenant-secret
