kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: developeruser-lfalero-uat
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  username: lfalero
  passwordCredentialsRef:
    name: developeruser-lfalero-uat-secret
  email: lfalero@redhat.com
  role: admin
  developerAccountRef:
    name: developeraccount-devsecops-uat
  providerAccountRef:
    name: uat-tenant-secret
