apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

configMapGenerator:
  - name: reconcile-script
    files:
      - reconcile_apps.py

generatorOptions:
  disableNameSuffixHash: true
