apiVersion: capabilities.3scale.net/v1beta1
kind: Application
metadata:
  name: application-sample-openid
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  name: "OpenID Test App"
  description: "Sample application configured with OpenID authentication"
  accountCR:
    name: developeraccount-devsecops-uat
  productCR:
    name: bs-hello-java-openid
  applicationPlanName: basic
  suspend: false
