apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-apicast-app-testing
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: noprod
  template:
    metadata:
      name: "{{name}}-apicast-app-testing"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-3scale-app.git
        targetRevision: develop
        path: "./overlays/middleware-apicast/noprod/testing"
      destination:
        server: "{{server}}"
        namespace: "apicast-gateway"
      #syncPolicy:
        #automated:
          #prune: true
          #selfHeal: true
