apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - developer-accounts/developeraccount-devsecops.yaml
  - developer-users/developeruser-lfalero-secret.yaml
  - developer-users/developeruser-lfalero.yaml

  - backends/bs-hello-java.yaml

  - products/bs-hello-java-api-key.yaml
  - applications/application-sample-api-key.yaml
  - application-auths/applicationauth-sample-api-key-secret.yaml
  - application-auths/applicationauth-sample-api-key.yaml

  - products/bs-hello-java-key-pair.yaml
  - applications/application-sample-key-pair.yaml
#  - application-auths/applicationauth-sample-key-pair-secret.yaml
#  - application-auths/applicationauth-sample-key-pair.yaml
